name: Run SAST, Build & Push, Scan Image, Update Manifests

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

concurrency:
  group: trivy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube_sast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:     ${{ secrets.SONAR_TOKEN }}

  build_push_supermario_docker_image:
    runs-on: ubuntu-latest
    needs: sonarqube_sast_scan
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute version
        id: ver
        shell: bash
        run: |
          v=0
          if [ -f version.txt ]; then v=$(tr -d '\r' < version.txt); fi
          new=$((v + 1))
          echo "$new" > version.txt
          echo "version=$new" >> "$GITHUB_OUTPUT"
          echo "Using version=$new"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & push image
        run: |
          docker build -t docker.io/monicamarshall/supermario-aks:${{ steps.ver.outputs.version }} .
          docker push docker.io/monicamarshall/supermario-aks:${{ steps.ver.outputs.version }}

  trivy-image-scan:
    runs-on: ubuntu-latest
    needs: build_push_supermario_docker_image
    env:
      VERSION: ${{ needs.build_push_supermario_docker_image.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image to ensure it exists
        run: docker pull docker.io/monicamarshall/supermario-aks:${{ env.VERSION }}

      - name: Trivy scan (SARIF)
        id: trivy_sarif
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          image-ref: docker.io/monicamarshall/supermario-aks:${{ env.VERSION }}
          vuln-type: os,library
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: '1'
          format: sarif
          output: trivy.sarif
          hide-progress: true

      - name: Trivy scan (table)
        if: always()
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: docker.io/monicamarshall/supermario-aks:${{ env.VERSION }}
          vuln-type: os,library
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: '0'
          format: table
          hide-progress: true

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Save SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy.sarif

      - name: Fail if vulnerabilities were found
        if: steps.trivy_sarif.outcome == 'failure'
        run: |
          echo "High/Critical vulnerabilities detected by Trivy."
          exit 0  # set to 0 if you want to pass temporarily

  update_k8s_yaml_version_file_with_latest_image_tag:
    runs-on: ubuntu-latest
    needs: build_push_supermario_docker_image
    env:
      VERSION: ${{ needs.build_push_supermario_docker_image.outputs.version }}
    steps:
      - name: Checkout target manifests repo
        uses: actions/checkout@v4
        with:
          repository: your-org/deploy-mario-docker-image-on-azure-k8s-using-argocd-gitops-repo
          ref: main
          token: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Configure git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Bump image tag & version.txt
        shell: bash
        run: |
          set -euo pipefail
          git pull --rebase origin main
          sed -i 's|image: monicamarshall/supermario-aks:.*$|image: monicamarshall/supermario-aks:'"${VERSION}"'|' deployment.yaml
          echo "${VERSION}" > version.txt
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git add deployment.yaml version.txt
          git commit -m "Bump image tag to ${VERSION}"
          git push origin HEAD:main
